// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/northmule/gophermart/internal/app/storage (interfaces: DBQuery,TxDBQuery)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/storage/mock/storage_mock.go -package=mocks github.com/northmule/gophermart/internal/app/storage DBQuery,TxDBQuery
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBQuery is a mock of DBQuery interface.
type MockDBQuery struct {
	ctrl     *gomock.Controller
	recorder *MockDBQueryMockRecorder
}

// MockDBQueryMockRecorder is the mock recorder for MockDBQuery.
type MockDBQueryMockRecorder struct {
	mock *MockDBQuery
}

// NewMockDBQuery creates a new mock instance.
func NewMockDBQuery(ctrl *gomock.Controller) *MockDBQuery {
	mock := &MockDBQuery{ctrl: ctrl}
	mock.recorder = &MockDBQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBQuery) EXPECT() *MockDBQueryMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDBQuery) Begin() (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBQueryMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDBQuery)(nil).Begin))
}

// ExecContext mocks base method.
func (m *MockDBQuery) ExecContext(arg0 context.Context, arg1 string, arg2 ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockDBQueryMockRecorder) ExecContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockDBQuery)(nil).ExecContext), varargs...)
}

// PingContext mocks base method.
func (m *MockDBQuery) PingContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockDBQueryMockRecorder) PingContext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockDBQuery)(nil).PingContext), arg0)
}

// Prepare mocks base method.
func (m *MockDBQuery) Prepare(arg0 string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", arg0)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockDBQueryMockRecorder) Prepare(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockDBQuery)(nil).Prepare), arg0)
}

// QueryContext mocks base method.
func (m *MockDBQuery) QueryContext(arg0 context.Context, arg1 string, arg2 ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockDBQueryMockRecorder) QueryContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockDBQuery)(nil).QueryContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockDBQuery) QueryRowContext(arg0 context.Context, arg1 string, arg2 ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockDBQueryMockRecorder) QueryRowContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockDBQuery)(nil).QueryRowContext), varargs...)
}

// MockTxDBQuery is a mock of TxDBQuery interface.
type MockTxDBQuery struct {
	ctrl     *gomock.Controller
	recorder *MockTxDBQueryMockRecorder
}

// MockTxDBQueryMockRecorder is the mock recorder for MockTxDBQuery.
type MockTxDBQueryMockRecorder struct {
	mock *MockTxDBQuery
}

// NewMockTxDBQuery creates a new mock instance.
func NewMockTxDBQuery(ctrl *gomock.Controller) *MockTxDBQuery {
	mock := &MockTxDBQuery{ctrl: ctrl}
	mock.recorder = &MockTxDBQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxDBQuery) EXPECT() *MockTxDBQueryMockRecorder {
	return m.recorder
}

// AddError mocks base method.
func (m *MockTxDBQuery) AddError(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddError", arg0)
}

// AddError indicates an expected call of AddError.
func (mr *MockTxDBQueryMockRecorder) AddError(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddError", reflect.TypeOf((*MockTxDBQuery)(nil).AddError), arg0)
}

// Commit mocks base method.
func (m *MockTxDBQuery) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxDBQueryMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTxDBQuery)(nil).Commit))
}

// Error mocks base method.
func (m *MockTxDBQuery) Error() []error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].([]error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockTxDBQueryMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockTxDBQuery)(nil).Error))
}

// QueryRowContext mocks base method.
func (m *MockTxDBQuery) QueryRowContext(arg0 context.Context, arg1 string, arg2 ...any) (*sql.Row, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockTxDBQueryMockRecorder) QueryRowContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockTxDBQuery)(nil).QueryRowContext), varargs...)
}

// Rollback mocks base method.
func (m *MockTxDBQuery) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxDBQueryMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTxDBQuery)(nil).Rollback))
}

// Tx mocks base method.
func (m *MockTxDBQuery) Tx() *sql.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tx")
	ret0, _ := ret[0].(*sql.Tx)
	return ret0
}

// Tx indicates an expected call of Tx.
func (mr *MockTxDBQueryMockRecorder) Tx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tx", reflect.TypeOf((*MockTxDBQuery)(nil).Tx))
}
